apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.namespace | quote }}
  name: {{ .Values.elasticsearch.name | quote }}
  labels:
     app: {{ .Values.elasticsearch.label.app | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.label.app | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.label.app | quote }}
    spec:
      containers:
        - name: {{ .Values.elasticsearch.container.name | quote }}
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
            limits:
              memory: "4096Mi"
              cpu: "1000m"
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ELASTIC_SEARCH_PASSWORD
            - name: xpack.security.enabled
              value: {{ .Values.elasticsearch.elastic_security_enabled | quote }}
          ports:
            - containerPort: 9200
            - containerPort: 9300
          {{ if eq .Values.healthCheck "true" }}
          readinessProbe:
            exec:
              command:
                - "curl"
                - "-f"
                - "localhost:9200/_cluster/health"
                - "--header"
                - "Authorization: Basic ZWxhc3RpYzpEa0llZFBQU0Ni"
            initialDelaySeconds: {{ .Values.initialdelay }}
            periodSeconds: {{ .Values.interval }}
            timeoutSeconds: {{ .Values.timeout }}
            failureThreshold: {{ .Values.retries }}
          {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.namespace | quote }}
  name: {{ .Values.elasticsearch.servicename | quote }}
spec:
  selector:
    app: {{ .Values.elasticsearch.label.app | quote }}
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  type: ClusterIP
