apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.namespace | quote }}
  name: {{ .Values.kafka.name | quote }}
  labels:
    app: {{ .Values.kafka.label.app | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.label.app | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.label.app | quote }}
    spec:
      containers:
      - name: {{ .Values.kafka.container.name | quote }}
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Values.zookeeper.servicename }}:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://{{ .Values.kafka.servicename }}:9092,OUTSIDE://localhost:9094"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
         {{ if eq .Values.healthCheck "true" }}
        # livenessProbe:
        #   exec:
        #     command:
        #      - kafka-topics
        #      - --list
        #      - --zookeeper
        #      - zookeeper:2181
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        #   failureThreshold: 10
        # readinessProbe:
        #   exec:
        #     command:
        #      - kafka-topics
        #      - --list
        #      - --zookeeper
        #      - zookeeper:2181
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        #   failureThreshold: 10
         {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.namespace | quote }}
  name: {{ .Values.kafka.servicename | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafka.label.app | quote }}
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
