apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Release.namespace | quote }}
  name: {{ .Values.redis.name | quote }}
spec:
  containers:
    - name: {{ .Values.redis.name | quote }}
      image: redis:latest
      ports:
        - containerPort: 6379
